plataforma:
    path:     /
    defaults: { _controller: "uniMisJuegosBundle:plataforma:index" }

plataforma_show:
    path:     /{id}/show
    defaults: { _controller: "uniMisJuegosBundle:plataforma:show" }

plataforma_new:
    path:     /new
    defaults: { _controller: "uniMisJuegosBundle:plataforma:new" }

plataforma_create:
    path:     /create
    defaults: { _controller: "uniMisJuegosBundle:plataforma:create" }
    requirements: { _method: post }

plataforma_edit:
    path:     /{id}/edit
    defaults: { _controller: "uniMisJuegosBundle:plataforma:edit" }

plataforma_update:
    path:     /{id}/update
    defaults: { _controller: "uniMisJuegosBundle:plataforma:update" }
    requirements: { _method: post|put }

plataforma_delete:
    path:     /{id}/delete
    defaults: { _controller: "uniMisJuegosBundle:plataforma:delete" }
    requirements: { _method: post|delete }
    
respPlat:
    path:     /respPlat
    defaults: { _controller: "uniMisJuegosBundle:plataforma:respPlat" }
